<?php

/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */

namespace Icinga\Module\Customdashboards\Controllers;

use Icinga\Data\Filter\FilterMatch;
use Icinga\Exception\Http\HttpMethodNotAllowedException;
use Icinga\Module\Customdashboards\MappingIniRepository;
use ipl\Html\Html;
use ipl\Web\Compat\CompatController;


class ExternalController extends CompatController
{

    public function indexAction(){
        if(intval($this->Config("config")->getSection('settings')->get("allow_external_urls",0)) === 0){
            $this->addContent(Html::tag('h2', null,$this->translate("External urls are not allowed!")));
            return;
        }
        $name = $this->params->getRequired('name');
        $dashlet = intval($this->params->getRequired('dashlet'));
        $forAllUsers = (new MappingIniRepository())->select()->addFilter(new FilterMatch('enabled','=',"1"))->addFilter(new FilterMatch('name','=',$name))->fetchAll();

        foreach ($forAllUsers as $mapping){
            $permission = 'customdashboards/mapping/'.$mapping->name;
            if($this->hasPermission($permission) || $this->hasPermission("customdashboards/mapping")){
                $mappings[$mapping->name]=$mapping;
            };

        }
        if(isset($mappings[$name]) && isset($mappings[$name]->{"dashleturl".$dashlet})){

            $this->addContent(Html::tag('iframe', ['src'=>$mappings[$name]->{"dashleturl".$dashlet}, 'width'=>'100%', 'height'=>'100%','frameborder'=>'no']),"<p>Your browser does not support iframes.</p>");
            $this->content->setAttribute("class","iframe-container");

        }else{
            throw new HttpMethodNotAllowedException("Permission denied!");
        }


    }


}
