<?php
/* Originally from Icinga Web 2 Elasticsearch Module (c) 2017 Icinga Development Team | GPLv2+ */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */
/* icingaweb2-module-customdashboards (c) 2023 | GPLv2+ */


namespace Icinga\Module\Customdashboards\Controllers;

use Icinga\Web\Controller;

use Icinga\Module\Customdashboards\Forms\MappingForm;
use Icinga\Module\Customdashboards\MappingIniRepository;

class MappingController extends Controller
{
    /**
     * Set the title tab
     *
     * @param   string  $label
     */
    public function setTitle($label)
    {
        $this->getTabs()->add(uniqid(), [
            'active'    => true,
            'label'     => $label,
            'url'       => $this->getRequest()->getUrl()
        ]);
    }


    public function init()
    {

    }

    public function indexAction()
    {
        $this->setTitle($this->translate('Panes'));
        if($this->hasPermission('customdashboards/mapping')){
            $this->view->configs = (new MappingIniRepository())->select();
        }else{
            $this->view->configs = (new MappingIniRepository())->select()->where('author',$this->auth->getUser()->getUsername());
        }


        $this->_helper->viewRenderer->setRender('mapping/table', null, true);
    }

    public function newAction()
    {
        $this->assertPermission('customdashboards/mapping');

        $form = new MappingForm([
            'mode'  => MappingForm::MODE_INSERT
        ]);

        $form->handleRequest();

        $this->setTitle($this->translate('New Pane'));

        $this->view->form = $form;

        $this->_helper->viewRenderer->setRender('form', null, true);
    }

    public function updateAction()
    {
        $id = $this->params->getRequired('id');

        if(! $this->hasPermission('customdashboards/mapping')){

            $model = (new MappingIniRepository())->select()->where('author',$this->auth->getUser()->getUsername())->where('name',$id)->fetchRow();
            if($model === false){
                throw new \Exception("Not Allowed");
            }
        }

        $form = new MappingForm([
            'mode'          => MappingForm::MODE_UPDATE,
            'identifier'    => $id
        ]);

        $form->handleRequest();


        $this->setTitle($this->translate('Update Pane'));

        $this->view->form = $form;

        $this->_helper->viewRenderer->setRender('form', null, true);
    }

    public function deleteAction()
    {
        $id = $this->params->getRequired('id');

        if(! $this->hasPermission('customdashboards/mapping')){

            $model = (new MappingIniRepository())->select()->where('author',$this->auth->getUser()->getUsername())->where('name',$id)->fetchRow();
            if($model === false){
                throw new \Exception("Not Allowed");
            }
        }

        $form = new MappingForm([
            'mode'          => MappingForm::MODE_DELETE,
            'identifier'    => $id
        ]);

        $form->handleRequest();

        $this->setTitle($this->translate('Remove Pane'));

        $this->view->form = $form;

        $this->_helper->viewRenderer->setRender('form', null, true);
    }
}
