<?php
/* Originally from Icinga Web 2 Reporting Module (c) Icinga GmbH | GPLv2+ */
/* generated by icingaweb2-module-scaffoldbuilder | GPLv2+ */
/* icingaweb2-module-customdashboards (c) 2023 | GPLv2+ */

namespace Icinga\Module\Customdashboards\Controllers;


use Icinga\Application\Config;
use Icinga\Web\Controller;
use Icinga\Module\Customdashboards\Forms\ModuleconfigForm;

class ModuleconfigController extends Controller
{

    /**
     * In case you want to use module config settings in this or any other controller this code is for you
     */
    private $settings_sometext;
    private $settings_somepassword;
    private $settings_somedropdown;
    private $settings_somecheckbox;

    public function init()
    {
        $this->assertPermission('config/modules');


        $this->settings_sometext = Config::module('icingacamp', "config")->get('settings', 'sometext') != null ?
            trim(Config::module('icingacamp', "config")->get('settings', 'settings_sometext'), "") : null;

        $this->settings_somepassword = Config::module('icingacamp', "config")->get('settings', 'somepassword') != null ?
            trim(Config::module('icingacamp', "config")->get('settings', 'somepassword'), "") : null;

        $this->settings_somedropdown = Config::module('icingacamp', "config")->get('settings', 'somedropdown') != null ?
            trim(Config::module('icingacamp', "config")->get('settings', 'somedropdown'), "") : null;

        $this->settings_somecheckbox = Config::module('icingacamp', "config")->get('settings', 'somecheckbox') != null ?
            trim(Config::module('icingacamp', "config")->get('settings', 'somecheckbox'), "") : null;

        parent::init();
    }


    public function indexAction()
    {
        $this->assertPermission('customdashboards/config');


        $form = (new ModuleconfigForm())
            ->setIniConfig(Config::module('customdashboards', "config"));

        $form->handleRequest();

        $this->view->tabs = $this->Module()->getConfigTabs()->activate('config/moduleconfig');
        $this->view->form = $form;
    }


    public function createTabs()
    {
        $tabs = $this->getTabs();

        $tabs->add('customdashboards/config', [
            'label' => $this->translate('Configure Customdashboards'),
            'url' => 'customdashboards/config'
        ]);

        return $tabs;

    }

}