<div class="controls">
    <?= /** @var \Icinga\Web\Widget\Tabs $tabs */ $tabs ?>
</div>
<div class="content">
    <div class="actions">
        <?php
        if(\Icinga\Authentication\Auth::getInstance()->hasPermission('customdashboards/mapping')){
            echo $this->qlink(
                $this->translate('Create a new Pane') ,
                'customdashboards/mapping/new',
                null,
                [
                    'class'             => 'button-link',
                    'data-base-target'  => '_next',
                    'icon'              => 'plus',
                    'title'             => $this->translate('Create a New Pane')
                ]
            );
        }
        ?>
    </div>
<?php /** @var \Icinga\Repository\RepositoryQuery $configs */ if (! $configs->hasResult()): ?>
    <p><?= $this->escape($this->translate('No Pane configured yet.')) ?></p>
<?php else: ?>
    <table class="common-table table-row-selectable" data-base-target="_next">
        <thead>
            <tr>
                <th><?= $this->escape($this->translate('Name')) ?></th>
                <th><?= $this->escape($this->translate('Priority')) ?></th>
                <th><?= $this->escape($this->translate('enabled')) ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($configs as $config): ?>
            <tr>
                <td><?= $this->qlink($config->name, 'customdashboards/mapping/update', ['id' => $config->name]) ?></td>
                <td><?= $config->priority ?></td>
                <td><?= $config->enabled==1?$this->translate('yes'):$this->translate('no') ?></td>
                <td class="icon-col"><?= $this->qlink(
                        null,
                        'customdashboards/mapping/delete',
                        array('id' => $config->name),
                        array(
                            'class' => 'action-link',
                            'icon'  => 'cancel',
                            'title' => $this->translate('Remove this Pane')
                        )
                    ) ?></td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
</div>
